### ISSUE TITLE
Exception preventing load with patch 6.11

### ISSUE THREAD

**Issue by peakzero** [lichie567/XIVAuras#43]
Box pops up saying it failed to load please restart. Error in Dalamud log below.

```2022-04-26 11:18:05.437 -04:00 [ERR] [XIVAuras] UiBuilder OnBuildUi caught exception
System.MissingMethodException: Method not found: 'UInt32 FFXIVClientStructs.FFXIV.Client.Game.ActionManager.GetActionStatus(FFXIVClientStructs.FFXIV.Client.Game.ActionType, UInt32, UInt32, UInt32, UInt32)'.
   at XIVAuras.Helpers.SpellHelpers.CanUseAction(UInt32 actionId, UInt32 targetId)
   at XIVAuras.Config.CooldownTrigger.IsTriggered(Boolean preview, DataSource& data) in D:\a\XIVAuras\XIVAuras\XIVAuras\Config\CooldownTrigger.cs:line 89
   at XIVAuras.Config.TriggerConfig.IsTriggered(Boolean preview, DataSource& data) in D:\a\XIVAuras\XIVAuras\XIVAuras\Config\TriggerConfig.cs:line 55
   at XIVAuras.Auras.AuraIcon.Draw(Vector2 pos, Nullable`1 parentSize, Boolean parentVisible) in D:\a\XIVAuras\XIVAuras\XIVAuras\Auras\AuraIcon.cs:line 181
   at XIVAuras.Auras.AuraGroup.Draw(Vector2 pos, Nullable`1 parentSize, Boolean parentVisible) in D:\a\XIVAuras\XIVAuras\XIVAuras\Auras\AuraGroup.cs:line 75
   at XIVAuras.Auras.AuraGroup.Draw(Vector2 pos, Nullable`1 parentSize, Boolean parentVisible) in D:\a\XIVAuras\XIVAuras\XIVAuras\Auras\AuraGroup.cs:line 75
   at XIVAuras.Auras.AuraGroup.Draw(Vector2 pos, Nullable`1 parentSize, Boolean parentVisible) in D:\a\XIVAuras\XIVAuras\XIVAuras\Auras\AuraGroup.cs:line 75
   at XIVAuras.PluginManager.Draw() in D:\a\XIVAuras\XIVAuras\XIVAuras\PluginManager.cs:line 87
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 305```

**Comment by peakzero** [comment]
Resolved with #44 
Thanks so much!
